/*
 * This source file was generated by the Gradle 'init' task
 */
package cs._final.project;
import java.awt.*;
import javax.swing.*;

public class App {
    public static void main(String[] args) {
        //Create Window
        JFrame frame = new JFrame("FILE CABINET");
        frame.setSize(800, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);


        JButton CreateNoteButton = new JButton();
    }

    public void CreateNote(){
        System.out.println("New Note");
    }
}
