/*
 * This source file was generated by the Gradle 'init' task
 */
package cs._final.project;

public class App {
    public static void main(String[] args) {
        NoteManager manager = new NoteManager();
    }
}
